### ISSUE TITLE
GaussianObservation.probability always returns zero

### ISSUE THREAD

**Issue by bpisaacoff** [lucasmaystre/kickscore#10]
I'm trying to use the difference model, but all the returned probabilities are (0, 1), which looking at the code 
```
prob = GaussianObservation.probability(items, threshold, var, t=t)
return (prob, 1 - prob)
```
suggests that the `GaussianObservation.probability` is always returning zero. Any idea what's going on? I'm getting the same issue with the CountDiffModel as well. 

My setup is below
```
model = ks.DifferenceModel()
kernel = (ks.kernel.Constant(var=0.03)
        + ks.kernel.Matern32(var=0.138, lscale=1.753*seconds_in_year))

for game in games:
   determine winner, loser, point differential, and game timestamp t
   observations.append({'items1': [winner],
                         'items2': [loser],
                         'diff': point differential,
                         't': t,
                         })
for obs in observations:
    model.observe(**obs)
    
converged = model.fit()

preds = []
for game in future_games:
   preds.append(model.probabilities([home_team], [away_team], game_timestamp)
```
which gives all the preds as (0,1)

**Comment by lucasmaystre** [comment]
The exact code in your last message runs when I execute it in a google colab, modifying the example here:
https://colab.research.google.com/github/lucasmaystre/kickscore/blob/master/examples/nba-history.ipynb

Probably something due to your platform?

Note that the NBA dataset is an example where the difference between two teams of similar strength can easily be in the double digits, so setting `var=100**2` or even higher might make it more stable.

**Comment by lucasmaystre** [comment]
Ah, got it. The issue is that the third argument of `model.probabilities()` is not `t`, but some threshold that can be used to rescale the observations, c.f.:
https://github.com/lucasmaystre/kickscore/blob/master/kickscore/observation/gaussian.py#L34

If you change your code to

```
print(model.probabilities([row["team2"]],[row["team1"]], t=t+1))
print(model.probabilities([row["team1"]],[row["team2"]], t=t+1))
```

that should do the trick.

**Comment by bpisaacoff** [comment]
AHHHHH! It's usually something totally dumb like that isn't it? That resolved it, and is a lesson to all of us to always use keyword arguments. Thank you so much for your help, I really appreciate it.

**Comment by lucasmaystre** [comment]
Glad we managed to track it down!
